remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sass-converter

title: "Lance Brady Analytics"
description: "A repository of baseball analytics research, multivariate analysis, and scouting samples."
baseurl: "/baseball-analytics/"
url: "https://lance-brady-analytics.github.io"
author: lance

# Enable author profile and sidebar globally
author_profile: true
sidebar: true

sass:
  sass_dir: assets/css   # Where your SCSS files are located

defaults:
  # Ensure sidebars are enabled for posts
  - scope:
      path: ""
      type: "posts"
    values:
      sidebar: true
      author_profile: true
  # Ensure sidebars are enabled for pages
  - scope:
      path: ""
      type: "pages"
    values:
      sidebar: true
      author_profile: true

# Minimal Mistakes navigation menu configuration
navigation: []

# Additional settings for Minimal Mistakes
minimal_mistakes_skin: "default"
fontawesome: true
